/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("common.kotlin-application-conventions")
    kotlin("plugin.serialization") version "1.8.10"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0")
}

application {
    // Define the main class for the application.
    mainClass.set("common.app.AppKt")
}
